wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1658758769
    t:
      1:
      - 3
      - 55
      4: 3.6.9
      5: 0.12.21
      8:
      - 5
